### ISSUE TITLE
Setting -m 4 blocks window event 7 from being produced.

### ISSUE THREAD

**Issue by lwilletts** [wmutils/opt#10]
Similar issues if you uncomment XCB_EVENT_MASK_BUTTON_PRESS in the source and compile it with XCB_EVENT_MASK_ENTER_WINDOW enabled.

[I also recorded an example.](https://www.youtube.com/watch?v=qv--XF76IfI)

**Comment by pockata** [comment]
@wildefyr, a bit late, but this looks like expected behavior. It's how masks work.
If you want to listen for `XCB_MASK_BUTTON_PRESS` and `XCB_EVENT_MASK_ENTER_WINDOW`, you need to run `wew -m 20`

Please note that currently when listening to `XCB_EVENT_MASK_BUTTON_PRESS` the keypress/keyrelease events do not get passed down to the window (which renders it rather useless).
I'm working on a fix as discussed in #8. I have a partial solution up and running, but it has a caveat - only the keypress event gets passed down to the window, and the keyrelease gets lost in the wind.

**Comment by lwilletts** [comment]
Yes you're quite right it seems! I look forward to this fix. (goodbye sloppy mouse!)

**Comment by z3bra** [comment]
If all you want is click-to-focus, there is much much simpler than using `wew`.

```
~button1
    focus.sh $(underneath)
```

I though that was your goal for creating this script! Looks like I was wrong

**Comment by lwilletts** [comment]
Yes, it doesn't quite work properly with dropdown menus and the like though, otherwise it's a decent solution.
