### ISSUE TITLE
`wew` doesn't print window focus events if the mouse isn't on a window

### ISSUE THREAD

**Issue by eepykate** [wmutils/opt#44]
wm: bspwm v0.9.7-10

**Comment by eepykate** [comment]
Tagging @z3bra as it appears he was the one to write it.

**Comment by lwilletts** [comment]
I have noticed an issue where if a wm is active before wew is called, wew will not receive several events. I guess this is a limitation because the wm catches them before they get sent.

**Comment by z3bra** [comment]
> I have noticed an issue where if a wm is active before wew is called,
> wew will not receive several events. I guess this is a limitation because
> the wm catches them before they get sent.

This is not an issue, this is how the X11 protocol works. To act as a WM,
a program has to redirect some events to itself rather that having them
passed directly to the X server.

What the WM does when it receives these events is up itself, and the X
server has no control over it. This means that other programs like `wew`
won't receive them because they are already redirected to the WM.

Practically speaking, when a new window is created, the event is reported
to bspwm that does whatever with it (add decorations, resize other
windows, …), and then discard the event.

`wew` won't get notified that a new window is created, and thus, won't
be able to add an event listener onto that window, thus no event can be
reported onto that window.

As for the focus events, it just happens that depending on where your
pointer is defines who receives the event. When a pointer is on a window,
this window is likely to report an event. When the pointer is on the
root window, then it depends on how the WM listen for events…

The issue originaly reported is more a "compatibility" issue than anything
else, and unfortunately this is not something that can be fixed on
`wew` side.

If you want it to work as expected, run `wew` without a WM.
